[project]
authors = [{name = "N283T", email = "w255508b@yokohama-cu.ac.jp"}]
dependencies = []
name = "pxr-iduction-challenge"
requires-python = ">= 3.11"
version = "0.1.0"

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tool.pixi.pypi-dependencies]
pxr_iduction_challenge = { path = ".", editable = true }

[tool.pixi.tasks]
db-start = "pg_ctl -D db/pgdata -l db/pgdata/logfile -o '-k /tmp -p 5433' start"
db-stop = "pg_ctl -D db/pgdata stop"
db-status = "pg_ctl -D db/pgdata status"
db-psql = "psql -h /tmp -p 5433 -d pxr_challenge"

[tool.pixi.dependencies]
python = "3.12.*"
postgresql = ">=18.3,<19"
rdkit = ">=2026.3.1,<2027"
rdkit-postgresql = ">=2026.3.1,<2027"
pandas = ">=3.0.2,<4"
pyarrow = ">=23.0.1,<24"
plotly = ">=6.6.0,<7"
marimo = ">=0.21.1,<0.22"
tabulate = ">=0.10.0,<0.11"
psycopg2 = ">=2.9.11,<3"
lightgbm = ">=4.6.0,<5"
scikit-learn = ">=1.8.0,<2"
chembl_structure_pipeline = ">=1.2.4,<2"
mordredcommunity = ">=2.0.7,<3"
