"""Caruana_bag20 bakeoff: 9-pool baseline vs +tabpfn_admet_ai_umap.

After tabpfn_admet_ai_umap was generated by run_admet_ai_tabpfn.py
(single OOF MAE 0.5156, Sp 0.7115), check whether caruana_bag20
allocates non-trivial weight to it given its orthogonality to the
existing 9 pool members (all SMILES embedding based).

Codex success criterion: caruana weight >= 1-5% AND OOF MAE Δ <= -0.003.

No DB writes. Standalone diagnostic.

Spec: docs/superpowers/specs/2026-04-29-admet-ai-features-design.md
"""

from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import psycopg2
from scipy.stats import spearmanr

REPO_ROOT = Path(__file__).resolve().parents[1].parent
sys.path.insert(0, str(REPO_ROOT.joinpath("track1_activity", "src")))
sys.path.insert(0, str(REPO_ROOT.joinpath("track1_activity", "scripts")))
from data import DB_PARAMS, load_train_smiles_target  # noqa: E402
from run_ensemble import ENSEMBLE_MODELS, optimize_caruana  # noqa: E402

NEW_MEMBER = "tabpfn_admet_ai_umap"


def load_member_oof(name: str) -> np.ndarray:
    with psycopg2.connect(**DB_PARAMS) as conn:
        cur = conn.cursor()
        cur.execute(
            "SELECT id FROM experiments WHERE name = %s ORDER BY id DESC LIMIT 1",
            (name,),
        )
        row = cur.fetchone()
        if row is None:
            raise RuntimeError(f"missing experiment: {name}")
        exp_id = row[0]
        cur.execute(
            """
            SELECT train_idx, oof_prediction
              FROM experiment_oof_predictions
             WHERE experiment_id = %s
             ORDER BY train_idx
            """,
            (exp_id,),
        )
        rows = cur.fetchall()
    if not rows:
        raise RuntimeError(f"no OOF predictions for {name} (id={exp_id})")
    return np.asarray([r[1] for r in rows], dtype=np.float64)


def caruana_bagged(oof_matrix: np.ndarray, y: np.ndarray, names: list[str]) -> dict:
    """Run optimize_caruana 5 times, average weights for stability."""
    weights_runs = []
    for seed in [42, 43, 44, 45, 46]:
        w = optimize_caruana(
            oof_matrix, y, n_iter=100, init_top_n=3, n_bags=20, seed=seed
        )
        weights_runs.append(w)
    weights_mean = np.mean(weights_runs, axis=0)
    weights_mean = weights_mean / weights_mean.sum()
    blend = oof_matrix @ weights_mean
    mae = float(np.mean(np.abs(blend - y)))
    sp = float(spearmanr(blend, y).statistic)
    return {
        "weights": dict(zip(names, [round(float(w), 4) for w in weights_mean])),
        "mae": mae,
        "sp": sp,
    }


def main() -> None:
    print("Loading train labels ...")
    train_df = load_train_smiles_target()
    y = train_df["pec50"].to_numpy(dtype=np.float64)
    print(f"  train n={len(y)}")

    print(f"\nLoading {len(ENSEMBLE_MODELS)}-pool OOF (current production) ...")
    base_names = list(ENSEMBLE_MODELS)
    base_oofs = []
    for name in base_names:
        oof = load_member_oof(name)
        if len(oof) != len(y):
            raise RuntimeError(f"{name}: OOF length {len(oof)} != y length {len(y)}")
        base_oofs.append(oof)
        print(f"  {name}: mean={oof.mean():.3f} std={oof.std():.3f}")
    base_matrix = np.column_stack(base_oofs)

    print(f"\nLoading new member: {NEW_MEMBER}")
    new_oof = load_member_oof(NEW_MEMBER)
    if len(new_oof) != len(y):
        raise RuntimeError(
            f"{NEW_MEMBER}: OOF length {len(new_oof)} != y length {len(y)}"
        )
    single_mae = float(np.mean(np.abs(new_oof - y)))
    single_sp = float(spearmanr(new_oof, y).statistic)
    print(f"  {NEW_MEMBER}: single OOF MAE={single_mae:.4f} Sp={single_sp:.4f}")

    print(f"\nResidual correlation of {NEW_MEMBER} vs each base member:")
    for base_name, base_oof in zip(base_names, base_oofs):
        r = float(np.corrcoef(new_oof, base_oof)[0, 1])
        print(f"    r vs {base_name:>60} = {r:+.4f}")

    print("\n=== Bakeoff: 2 caruana_bag20 variants (5-seed averaged weights) ===")
    variants = {
        "baseline_9pool": (base_names, base_matrix),
        "+admet_ai": (
            base_names + [NEW_MEMBER],
            np.column_stack([base_matrix, new_oof]),
        ),
    }

    baseline_mae = None
    baseline_sp = None
    for variant_name, (names, matrix) in variants.items():
        print(f"\n--- {variant_name} ({len(names)} members) ---")
        result = caruana_bagged(matrix, y, names)
        if variant_name == "baseline_9pool":
            baseline_mae = result["mae"]
            baseline_sp = result["sp"]
        delta_mae = result["mae"] - baseline_mae if baseline_mae is not None else 0.0
        delta_sp = result["sp"] - baseline_sp if baseline_sp is not None else 0.0
        print(
            f"  caruana OOF MAE = {result['mae']:.4f}  Δ vs baseline = {delta_mae:+.4f}"
        )
        print(
            f"  caruana OOF Sp  = {result['sp']:.4f}  Δ vs baseline = {delta_sp:+.4f}"
        )
        print("  weights (top by magnitude):")
        sorted_w = sorted(result["weights"].items(), key=lambda x: -x[1])
        for n, w in sorted_w:
            highlight = " <-- NEW" if n == NEW_MEMBER else ""
            print(f"    {w:.4f}  {n}{highlight}")
        if NEW_MEMBER in result["weights"]:
            w = result["weights"][NEW_MEMBER]
            if w >= 0.01:
                print(f"  PASS: {NEW_MEMBER} weight {w:.4f} >= 1% threshold")
            else:
                print(f"  WARN: {NEW_MEMBER} weight {w:.4f} < 1% threshold")

    # Family share check (chemprop family = top 3 in current pool)
    chemprop_family = {
        "tabpfn_cheme_2d_full_boltz_log2fc_pred_optuna_trial10_seed5ens_umap_default",
        "tabpfn_chemprop_pretrain_embed_umap_default",
        "tabpfn_cheme_2d_full_boltz_log2fc_pred_seed10ens_top500_umap",
    }
    print("\nFamily share check (chemprop):")
    for variant_name, (names, matrix) in variants.items():
        result = caruana_bagged(matrix, y, names)
        share = sum(result["weights"].get(n, 0) for n in chemprop_family)
        in_zone = 0.65 <= share <= 0.80
        print(
            f"  {variant_name}: chemprop family share = {share:.3f}  "
            f"({'in 0.65-0.80 zone' if in_zone else 'OUT of zone'})"
        )


if __name__ == "__main__":
    main()
