"""TabPFN on ADMET-AI 104 features (standalone pool member candidate).

Loads predictions from data/admet_ai_predictions.parquet (generated by
run_admet_ai_predict.py), trains TabPFN on UMAP 5-fold CV, records the
experiment + OOF + submission CSV for caruana ensemble consumption.

Pool member name: tabpfn_admet_ai_umap

Spec: docs/superpowers/specs/2026-04-29-admet-ai-features-design.md
"""

from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pandas as pd

REPO_ROOT = Path(__file__).resolve().parents[1].parent
sys.path.insert(0, str(REPO_ROOT.joinpath("track1_activity", "src")))
from data import load_test_smiles, load_train_smiles_target  # noqa: E402
from evaluate import (  # noqa: E402
    compute_metrics,
    record_experiment,
    save_oof_predictions,
)
from splits import umap_split_indices  # noqa: E402

ADMET_PARQUET = REPO_ROOT.joinpath("data", "admet_ai_predictions.parquet")
SUBMISSION_DIR = REPO_ROOT.joinpath("track1_activity", "submissions")
EXPERIMENT_NAME = "tabpfn_admet_ai_umap"

N_SPLITS = 5
N_CLUSTERS = 50
SEED = 42

TABPFN_PARAMS = {
    "n_estimators": 8,
    "device": "cuda",
    "softmax_temperature": 0.9,
    "random_state": 42,
    "ignore_pretraining_limits": True,
}


def load_admet_features() -> tuple[np.ndarray, np.ndarray, list[str]]:
    """Return (X_train, X_test, feature_names) aligned to load_*_smiles order."""
    if not ADMET_PARQUET.exists():
        raise RuntimeError(
            f"{ADMET_PARQUET} not found; run run_admet_ai_predict.py first"
        )
    df = pd.read_parquet(ADMET_PARQUET)
    feat_cols = [c for c in df.columns if c not in ("smiles", "smiles_idx", "is_train")]
    train = df.loc[df["is_train"]].sort_values("smiles_idx")
    test = df.loc[~df["is_train"]].sort_values("smiles_idx")
    X_train = train[feat_cols].to_numpy(dtype=np.float64)
    X_test = test[feat_cols].to_numpy(dtype=np.float64)
    return X_train, X_test, feat_cols


def main() -> None:
    print("Loading data ...")
    train_df = load_train_smiles_target()
    test_df = load_test_smiles()
    y_train = train_df["pec50"].to_numpy(dtype=np.float64)

    X_train, X_test, feat_cols = load_admet_features()
    if len(X_train) != len(train_df):
        raise RuntimeError(
            f"feature train rows {len(X_train)} != train_df {len(train_df)}"
        )
    if len(X_test) != len(test_df):
        raise RuntimeError(f"feature test rows {len(X_test)} != test_df {len(test_df)}")
    print(f"  train={len(X_train)}, test={len(X_test)}, n_features={len(feat_cols)}")

    print(
        f"Building UMAP {N_SPLITS}-fold split (Morgan+Jaccard, k={N_CLUSTERS}, seed={SEED}) ..."
    )
    folds = umap_split_indices(
        train_df["smiles"].tolist(),
        n_splits=N_SPLITS,
        n_clusters=N_CLUSTERS,
        seed=SEED,
    )
    print(f"  built {len(folds)} folds")

    print("Cross-validating TabPFN on ADMET-AI features ...")
    from tabpfn import TabPFNRegressor

    oof_preds = np.zeros(len(X_train), dtype=np.float64)
    fold_metrics = []
    for fi, (tr_idx, va_idx) in enumerate(folds):
        model = TabPFNRegressor(**TABPFN_PARAMS)
        model.fit(X_train[tr_idx], y_train[tr_idx])
        oof_preds[va_idx] = model.predict(X_train[va_idx])
        m = compute_metrics(y_train[va_idx], oof_preds[va_idx])
        fold_metrics.append(m)
        print(
            f"  fold {fi}: train={len(tr_idx)} val={len(va_idx)} "
            f"MAE={m['MAE']:.4f}  RAE={m['RAE']:.4f}  Sp={m['Spearman_R']:.4f}"
        )
    overall = compute_metrics(y_train, oof_preds)
    print(
        f"  full OOF: MAE={overall['MAE']:.4f}  RAE={overall['RAE']:.4f}  "
        f"Sp={overall['Spearman_R']:.4f}  R2={overall['R2']:.4f}"
    )

    print("Fitting on ALL train (for test prediction) ...")
    full_model = TabPFNRegressor(**TABPFN_PARAMS)
    full_model.fit(X_train, y_train)
    test_preds = full_model.predict(X_test)
    print(
        f"  test preds: mean={test_preds.mean():.4f} std={test_preds.std():.4f} "
        f"min={test_preds.min():.4f} max={test_preds.max():.4f}"
    )

    # Submission CSV
    sub = pd.DataFrame(
        {
            "SMILES": test_df["smiles"],
            "Molecule Name": test_df["molecule_name"],
            "pEC50": test_preds,
        }
    )
    sub_path = SUBMISSION_DIR.joinpath(f"{EXPERIMENT_NAME}.csv")
    sub.to_csv(sub_path, index=False)
    print(f"  wrote {sub_path}")

    # Record DB
    exp_id = record_experiment(
        name=EXPERIMENT_NAME,
        description="TabPFN on ADMET-AI 104 features (Stanford Swanson, TDC benchmark)",
        model_type="tabpfn",
        feature_set="admet_ai_104",
        hyperparameters={
            **TABPFN_PARAMS,
            "n_features": len(feat_cols),
            "n_splits": N_SPLITS,
            "n_clusters": N_CLUSTERS,
            "seed": SEED,
        },
        fold_metrics=fold_metrics,
        submission_path=f"track1_activity/submissions/{EXPERIMENT_NAME}.csv",
        notes=(
            f"OOF MAE={overall['MAE']:.4f}, ADMET-AI standalone, "
            "Codex orthogonal-info pivot 2026-04-29"
        ),
        on_conflict_replace=True,
    )
    save_oof_predictions(exp_id, oof_preds)
    print(f"\nDone. Experiment id={exp_id}, name={EXPERIMENT_NAME}")
    print(f"  OOF: MAE={overall['MAE']:.4f}  Sp={overall['Spearman_R']:.4f}")


if __name__ == "__main__":
    main()
